let a = 42;
 let b = "Bonjour";
 let c = true;
 let d = null;
 let e ;
 let f = [1, 2, 3];
 let g = { nom: "Ali" };
 let h = NaN;
 console.log( String(a),"->",typeof a);
 console.log( String(b),"->",typeof b);
 console.log( String(c),"->",typeof c);
 console.log( String(d),"->",typeof d);
 console.log( String(e),"->",typeof e);
 console.log( String(f),"->",typeof f);
 console.log( String(g),"->",typeof g);
 console.log( String(h),"->",typeof h);
 console.log("-------------------------------------------------------");
 console.log("---------------------métohde 2--------------------------");
 
 let variables=[a,b,c,d,e,f,g,h];
 variables.forEach( (v)  =>  console.log( String(v),"->",typeof v) );